### ISSUE TITLE
How much GPU memory do T2V-compbench need to evaluate?

### ISSUE THREAD

**Issue by shaoshitong** [KaiyueSun98/T2V-CompBench#2]
Thank you for your great work! However, I have some questions. How much GPU memory is needed to conduct an evaluation? Since I found that T2V-compbench relies on LLAVA, DepthAnything and Ground-DINO, I want to know if 24G is enough?

**Comment by KaiyueSun98** [comment]
Hi,
Thanks for your interest to our work!

For LLaVA, we use the [llava-v1.6-34b](https://huggingface.co/liuhaotian/llava-v1.6-34b) checkpoint for evaluation, which requires approximately **70 to 80GB of GPU memory**. However, you can easily run the LLaVA evaluation code on multiple GPUs by specifying which GPUs to use with `CUDA_VISIBLE_DEVICES`. Therefore, **4 GPUs with 24 GB each** will be sufficient. 

For DepthAnything, we use the [depth-anything-large](https://huggingface.co/spaces/LiheYoung/Depth-Anything/blob/main/checkpoints/depth_anything_vitl14.pth) checkpoint to obtain the depth maps of the video frames, which requires about **3.3GB GPU memory**, so a 24G GPU is enough. 

In addition, other models that T2V-CompBench relies on including GroundingDINO/GroundingSAM and DOT can also fit within a 24GB GPU.

If you still have any unsolved problems regarding our paper or codebase, please do not hesitate to contact us.

**Comment by shaoshitong** [comment]
Thanks for your replying! We've finished the evaluation and I think the stability of this benchmark is pretty good. However, it is really inconvenient to need different environments for different preference metrics, it would be better if the author can open a one-click installation of instruction or docker in the future.
